name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: 'Name of the artifact to download'
                type: string
                required: true
                default: 'dist'
        outputs:
            result:
                description: 'The result of the deployment operation'
                value: ${{ jobs.deploy.outputs.outcome}}
        # secrets:
        #     some-secret:
        #         description: 'A secret for deployment'
        #         required: false
jobs:
    deploy:
        outputs:
            outcome: ${{ steps.set-result.outputs.step-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v5
              with:
                    name: ${{ inputs.artifact-name }}
            - name: List files
              run: ls
            - name: Output information
              run: echo "Deploying & uploading ..."
            - name: Set result output
              id: set-result
              run: echo "step-result=Deployed successfully" >> $GITHUB_OUTPUT